Sys_Meeting/Controllers/MeetController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;
using System.Web.Mvc;
using Sys_Meeting.Models;

namespace Sys_Meeting.Controllers
{
    public class MeetController : Controller
    {
        //
        // GET: /Meet/
        //public string gConnectionString = SqlHelper.ReportCentreConnectionString;
        
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Add()
        {
            return View("Index");
        }

        [HttpPost]
        public ActionResult Add(MeetModels meetModels)
        {
            if (ModelState.IsValid)
            {
                string content = meetModels.Addr + meetModels.IdCard + meetModels.Name;
                return Content(content);
            }
            else
            {
                return Content("error!");
            }
        }

        public bool CheckIsLogin()
        {
            return Session["userid"] != null;
        }

        public string GetErrDescription(int ErrNum)
        {
            string sErrMsg = "";
            switch (ErrNum)
            {
                case -1:
                    sErrMsg = "登陸超時,請重新登陸！";
                    break;
            }
            return sErrMsg;
        }

        [HttpGet]
        public ActionResult ListDetail()
        {
            return View("ListDetail");
        }

        [HttpPost]
        public ActionResult ListDetail(MeetListModels meetListModels)
        {
            string sErrmsg = "";
            string guid = Guid.NewGuid().ToString().ToUpper();
            //string resultSuc = meetListModels.ListId + "," + meetListModels.ListName;
            string sql = "";
            int returnSuc = 0;

            if (Session["userid"] == null)
            {
                returnSuc = -1;
                sErrmsg = GetErrDescription(returnSuc);//"登陸超時,請重新登陸！";
                //return RedirectToAction("Login", "Account");
            }
            else
            {
                try
                {
                    if (meetListModels.ListAction == "create")
                    {
                        sql =
                            "insert into tb_list(sys_id,list_id,title,create_by) values(@sys_id,@list_id,@title,@create_by)";

                        returnSuc = DBCommon.SqlHelper.ExecuteNonQuery(DBCommon.SqlHelper.ConntionString, CommandType.Text,
                            sql
                            , new SqlParameter("@sys_id", guid)
                            , new SqlParameter("@list_id", meetListModels.ListId)
                            , new SqlParameter("@title", meetListModels.ListName)
                            , new SqlParameter("@create_by", Session["userid"].ToString()));
                    }
                    else if (meetListModels.ListAction == "edit")
                    {
                        sql =
                            "update tb_list set title=@title,modi_by=@modi_by,modi_dte=@modi_dte where sys_id=@sys_id and is_del=0";
                        returnSuc = DBCommon.SqlHelper.ExecuteNonQuery(DBCommon.SqlHelper.ConntionString, CommandType.Text,
                            sql
                            , new SqlParameter("@title", meetListModels.ListName)
                            , new SqlParameter("@modi_by", Session["userid"].ToString())
                            , new SqlParameter("@modi_dte", DateTime.Now.ToString("yyyy-MM-dd hh:mm:ss"))
                            , new SqlParameter("@sys_id", meetListModels.ListSysId));
                    }

                }
                catch (Exception e)
                {
                    sErrmsg = e.Message;
                    //throw;
                }
            }
            return Json(new { result = returnSuc, errmsg = sErrmsg });
        }

        //獲取事項列表
        public JsonResult GetList()
        {
            int totalrows = 0;
            var sql = new StringBuilder();
            sql.Append("exec sp_getPageData 'select @pagemark sys_id,list_id,title FROM tb_list WHERE 1=1 and is_del=0',@orderby,@pagenum,@pagesize");

            var page = 1;
            var rows = 10;

            if (!string.IsNullOrEmpty(Request.QueryString["page"]))
            {
                page = Convert.ToInt16(Request.QueryString["page"]);
            }
            if (!string.IsNullOrEmpty( Request.QueryString["rows"] ))
            {
                rows = Convert.ToInt16(Request.QueryString["rows"]);
            }
            //if (page == 1)
            //{
            SqlDataReader dr = DBCommon.SqlHelper.ExecuteReader(DBCommon.SqlHelper.ConntionString, CommandType.Text, "select count(1) totalrows FROM tb_list WHERE 1=1 and is_del=0");
            while (dr.Read())
            {
                totalrows = (int) dr["totalrows"];
            }
            //}
            DataSet ds = DBCommon.SqlHelper.ExecuteDataset(DBCommon.SqlHelper.ConntionString, CommandType.Text, sql.ToString()
                , new SqlParameter("@pagesize", rows)//每頁顯示記錄的數量
                , new SqlParameter("@pagenum", page)//當前頁
                ,new SqlParameter("@orderby","sys_id"));

            var list = new ArrayList();
            foreach (DataRow r in ds.Tables[0].Rows)
            {
                list.Add(new
                {
                    //rownum=r["rownum"].ToString(),
                    sys_id=r["sys_id"].ToString(),
                    list_id=r["list_id"].ToString(),
                    title=r["title"].ToString()
                });
            }
            //string json = DataTableConvertJson.Dataset2Json(ds);
            //json = "{\"total\":30,\"rows\":" + json + "}";
            //return Content(json);
            return Json(new { total = totalrows, rows = list }, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetListItem(string sysid)
        {

            //string connString = SqlHelper.ReportCentreConnectionString;
            string sql = "select top 1 sys_id,list_id,title from tb_list where is_del=0 and sys_id=@sys_id";
            DataSet ds = DBCommon.SqlHelper.ExecuteDataset(DBCommon.SqlHelper.ConntionString, CommandType.Text, sql
                , new SqlParameter("@sys_id", sysid));
            string returnJson = DataTableConvertJson.Dataset2Json(ds);
            int returnSuc = ds.Tables[0].Rows.Count;
            //returnJson = "{\result\":"+returnSuc+":" + returnJson + "}";
            string sErrmsg = "";
            string sListName = "";
            string sListId = "";
            if (returnSuc == 0)
            {
                sErrmsg = "事項不存在！";
            }
            else
            {
                sListId = ds.Tables[0].Rows[0]["list_id"].ToString();
                sListName = ds.Tables[0].Rows[0]["title"].ToString();
            }

            return Json(new { result = returnSuc, errmsg = sErrmsg,listid=sListId, listname = sListName });
            //return Content(returnJson);
        }

        public ActionResult DelListItem(string sysid)
        {
            int returnSuc = 0;
            string sql = "update tb_list set is_del=1,del_by=@del_by,del_dte=@del_dte where sys_id=@sys_id and is_del=0";
            string sErrmsg = "";
            if (CheckIsLogin())
            {
                try
                {
                    returnSuc = DBCommon.SqlHelper.ExecuteNonQuery(DBCommon.SqlHelper.ConntionString, CommandType.Text, sql
                        , new SqlParameter("@sys_id", sysid)
                        , new SqlParameter("@del_by", Session["userid"].ToString())
                        , new SqlParameter("@del_dte", DateTime.Now.ToString("yyyy-MM-dd hh:mm:ss")));
                }
                catch (Exception e)
                {
                    sErrmsg = e.Message;
                }
            }
            else
            {
                returnSuc = -1;
                sErrmsg = GetErrDescription(returnSuc);
            }
            return Json(new { result = returnSuc, errmsg = sErrmsg });
        }

        //搜索事項
        public ActionResult SearchList(string wd,string t)
        {
            string swhere = "";
            if (t == "事項編號")
            {
                swhere = " and (list_id like @wd)";
            }
            else if (t == "事項名稱")
            {
                swhere = " and (title like @wd)";
            }
            else
            {
                swhere = " and (1=1)";
            }

            string sql = "";
            sql = "select * from(";
            sql +=
                "select top (@pagenum * @pagesize) ROW_NUMBER() OVER (ORDER BY sys_id) AS rownum, sys_id,list_id,title FROM tb_list WHERE 1=1 and is_del=0 " +
                swhere;
            sql += ") as tb";
            sql += " where rownum between ( @pagenum - 1 )* @pagesize + 1 AND (@pagenum*@pagesize) order by rownum";

            int page = 1;
            int rows = 10;

            DataSet ds = DBCommon.SqlHelper.ExecuteDataset(DBCommon.SqlHelper.ConntionString, CommandType.Text, sql
                , new SqlParameter("@pagesize", rows)
                , new SqlParameter("@pagenum", page)
                , new SqlParameter("@wd", "%" + wd + "%"));

            string json = DataTableConvertJson.Dataset2Json(ds);
            json = "{\"total\":"+ds.Tables[0].Rows.Count+",\"rows\":" + json + "}";
            return Content(json);
        }

        //搜索會議記錄事項和內容
        //[HttpPost]
        public ActionResult Search()
        {
            return View("Search");
        }

        public JsonResult Searchmeet(SearchMeetModels searchMeetModels)
        {
            bool ret = false;
            int iTotal = 0, iRows = 0;
            string sErrmsg = "";

            if (Session["userid"] == null)
            {
                return Json(new {result = ret, total = iTotal, rows = iRows, errmsg = "登陸超時請重新登陸！"},

Sys_Meeting/Controllers/SearchController.cs
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Text;
using System.Web.Mvc;
using Sys_Meeting.Models;

namespace Sys_Meeting.Controllers
{
    public class SearchController : Controller
    {
        //
        // GET: /Search/
        //public List<SearchField> StatusToList()
        //{
        //    List<SearchField> list = new List<SearchField>();
        //    foreach (string statusName in Enum.GetNames(typeof(SearchField)))
        //    {
        //        list.Add((SearchField)statusName);
        //    }
        //    return list;
        //}
        [HttpPost]
        public ActionResult Result(SearchModels searchModels)
        {

            if (Session["userid"] == null)
            {
                return Json(new {total = 0, rows = "", result = false, errmsg = "登陸超時請重新登陸！",module=searchModels.Model});
            }

            string meetsysid = "";
            string mtid = "",title="",date="",time="",addr="";

            switch ((int)searchModels.Field)
            {
                case (int)SearchField.Id:
                    mtid = searchModels.Wd;
                    break;
                case(int)SearchField.Title:
                    title = searchModels.Wd;
                    break;
                case(int)SearchField.Date:
                    date = searchModels.Wd;
                    break;
                case (int)SearchField.Time:
                    time = searchModels.Wd;
                    break;
                case (int)SearchField.Addr:
                    addr = searchModels.Wd;
                    break;
                default:
                    return Json(new { result = "0", errmsg = "非法請求" });
            }

            
            StringBuilder sql = new StringBuilder();
            sql.Append("select * from(");
            sql.Append("select top (@pagenum * @pagesize) ROW_NUMBER() OVER (ORDER BY sys_dte) AS rownum, sys_id,mt_id,");
            sql.Append("title,mt_dte,mt_time,addr from tb_meet WHERE 1=1 and is_del=0 ");
            sql.Append(meetsysid == "" ? "" : " and sys_id='" + meetsysid + "'");
            sql.Append(mtid == "" ? "" : " and mt_id like '%" + mtid + "%'");
            sql.Append(title == "" ? "" : " and title like '%" + title + "%'");
            sql.Append(date == "" ? "" : " and mt_dte like '%" + date + "%'");
            sql.Append(time == "" ? "" : " and mt_time like '%" + time + "%'");
            sql.Append(addr == "" ? "" : " and addr like '%" + addr + "%'");

            sql.Append(") as tb");
            sql.Append(" where rownum between ( @pagenum - 1 )* @pagesize + 1 AND (@pagenum*@pagesize) order by rownum");

            int page = 1;
            int rows = 10;

            DataSet ds = DBCommon.SqlHelper.ExecuteDataset(DBCommon.SqlHelper.ConntionString, CommandType.Text, sql.ToString()
                , new SqlParameter("@pagesize", rows)
                , new SqlParameter("@pagenum", page));

            List<MeetMaintenanceModels> listRows = new List<MeetMaintenanceModels>();

            foreach (DataRow dr in ds.Tables[0].Rows)
            {
                listRows.Add(new MeetMaintenanceModels()
                {
                    sysid = dr["sys_id"].ToString(),
                    id = dr["mt_id"].ToString(),
                    date = dr["mt_dte"].ToString(),
                    time = dr["mt_time"].ToString(),
                    addr = dr["addr"].ToString(),
                    name = dr["title"].ToString()//,
                    //listitems = listItems,
                    //listmasters = listMasters,
                    //listjoins = listJoins,
                    //listunjoins = listUnJoins,
                    //listsharelists = listShares
                });
            }

            return Json(new { total = ds.Tables[0].Rows.Count, rows = listRows, result = true, errmsg = "", module = searchModels.Model });
            //return Json(new {result = "1", errmsg = ""});
        }

    }
}

Sys_Meeting/Views/Meet/Index.cshtml
@model Sys_Meeting.Models.MeetModels

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Index</title>
    <script src="~/Scripts/jquery-1.7.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
</head>
<body>
    
    
    @using (Html.BeginForm("add","Meet","Post")) {
        @Html.ValidationSummary(true)
    
        <fieldset>
            <legend>MeetModels</legend>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Name)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Name)
                @Html.ValidationMessageFor(model => model.Name)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Addr)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Addr)
                @Html.ValidationMessageFor(model => model.Addr)
            </div>
    
            <div class="editor-label">
                @Html.LabelFor(model => model.IdCard)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.IdCard)
                @Html.ValidationMessageFor(model => model.IdCard)
            </div>
    
            <p>
                <input type="submit" value="Create" />
            </p>
        </fieldset>
    }
    
    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</body>
</html>

Sys_Meeting/Views/Meet/Search.cshtml
@model Sys_Meeting.Models.SearchMeetModels

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>Search</title>
    <link rel="shortcut icon" href="../../Content/favicon.ico" type="image/x-icon" />
    <link href="../../Content/jquery-plugin/themes/icon.css" rel="stylesheet" type="text/css" />

    <script src="~/Scripts/jquery-1.7.1.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js" type="text/javascript"></script>

    <link href="../../Content/jquery-plugin/themes/metro/easyui.css" rel="stylesheet"
          type="text/css" />
    <link href="../../Content/jquery-plugin/demo/demo.css" rel="stylesheet" type="text/css" />
    <script src="http://localhost:52711/Content/jquery-plugin/jquery.form.js" type="text/javascript"></script>
    
    <script src="../../Content/jquery-plugin/jquery.easyui.min.js" type="text/javascript"></script>
    <script src="../../Content/jquery-plugin/locale/easyui-lang-zh_TW.js" type="text/javascript"></script>
    <script src="../../Content/js/CommonAction.js" type="text/javascript"></script>
    <script src="../../Content/js/HttpAction.js" type="text/javascript"></script>
</head>
<body>
    @using (Ajax.BeginForm("searchmeet", "meet", new AjaxOptions { HttpMethod = "GET", InsertionMode = InsertionMode.InsertBefore,UpdateTargetId = "returndata" }, new { method = "GET", id = "form-list" }))
    {
        @Html.ValidationSummary(true)
        <div id="returndata"></div>
        @*<fieldset>
            <legend>會議記錄查詢</legend>*@
    
            <div class="editor-label">
                @Html.LabelFor(model => model.Keywords)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Keywords)<label>多個關鍵字可用英文","號分隔.</label>
                @Html.ValidationMessageFor(model => model.Keywords)
            </div>
    
            <div class="editor-label" style="display: none">
                @Html.LabelFor(model => model.Listfrom)
            </div>
            <div class="editor-field" style="display: none">
                @Html.EditorFor(model => model.Listfrom)
                @Html.ValidationMessageFor(model => model.Listfrom)
                
                @Html.LabelFor(model => model.Listto)
                @Html.EditorFor(model => model.Listto)
                @Html.ValidationMessageFor(model => model.Listto)
            </div>
    
            

            <div class="editor-label">
                @Html.LabelFor(model => model.Meetdatefrom)
            </div>
            <div class="editor-field">
                @Html.EditorFor(model => model.Meetdatefrom)
                @Html.ValidationMessageFor(model => model.Meetdatefrom)
                
                @Html.LabelFor(model => model.Meetdateto)
                @Html.EditorFor(model => model.Meetdateto)
                @Html.ValidationMessageFor(model => model.Meetdateto)
            </div>
            
            <p>
                <input type="button" id="btn-search" value="搜索" />
            </p>
        @*</fieldset>*@
        
    }
    <div id="div-list-panels" class="easyui-accordion"></div>
    <div id="div-dailog-edit" style="display: none">
        <table>
            <tr>
                <th>報告日期：</th><td><input type="text" id="txtrptdte"/></td>
            </tr>
            <tr>
                <th>負責人：</th>
                <td>
                    <input type="text" id="txtactperson" readonly="readonly"/><input type="hidden" id="txtactperson_f" readonly="readonly"/>
                    <a href="javascript:void(0)" class="easyui-linkbutton" iconcls="icon-search" id="open-search"></a>
                </td>
            </tr>
            <tr>
                <th>行動：</th><td><textarea id="txtactcontent" cols="30" rows="4"></textarea></td>
            </tr>
                
        </table>
    </div>
    
    <div id="div-dailog-search" style="display: none"></div>

    <script type="text/javascript">
        var btnNew = '<a href="javascript:void(0)" class="easyui-linkbutton" iconCls="icon-add" id="btn-new">添加</a>';
        var btnEdit = '<a href="javascript:void(0)" class="btn-edit">';
        btnEdit += '<span class="l-btn-left l-btn-icon-left">';
        btnEdit += '<span class="l-btn-text"></span>';
        btnEdit += '<span class="l-btn-icon icon-edit"></span>';
        btnEdit += '</span>';
        btnEdit += '</a>';

        var btnDel = '<a href="javascript:void(0)" class="btn-del">';
        btnDel += '<span class="l-btn-left l-btn-icon-left">';
        btnDel += '<span class="l-btn-text"></span>';
        btnDel += '<span class="l-btn-icon icon-remove"></span>';
        btnDel += '</span>';
        btnDel += '</a>';

        var btnSave = '<a href="javascript:void(0)" class="btn-save">';
        btnSave += '<span class="l-btn-left l-btn-icon-left">';
        btnSave += '<span class="l-btn-text">保存</span>';
        btnSave += '<span class="l-btn-icon icon-save"></span>';
        btnSave += '</span>';
        btnSave += '</a>';

        $('#btn-search').click(function() {
            $('#form-list').ajaxSubmit(function (ret) {
                if (!ret.result) {
                    $.messager.alert('提示', ret.errmsg, 'info',function() {
                        return;
                    });
                }
                removeAllPanel();
                loadlist(ret);
            });
        });

        $(document).delegate('#btn-new', 'click', function () {
            var td = '<tr><td style="display:none"></td><td></td><td></td><td></td><td>' + btnEdit + '|' + btnDel + '</td></tr>';
            $(this).parent().parent().parent().parent().append(td);
        });

        $(document).delegate('.btn-del', 'click', function () {
            $(this).parents('tr').remove();
        });

        $(document).delegate('.btn-edit', 'click', function () {

            ClearActionModels();

            var oCols = $(this).parent().parent().children('td'); //.eq(0).text()  ;

            $('#txtactperson_f').val(oCols.eq(0).text());
            $('#txtactperson').val(oCols.eq(1).text());
            $('#txtactcontent').val(oCols.eq(2).text());
            $('#txtrptdte').val(oCols.eq(3).text());

            openDailog('#div-dailog-edit', '編輯', function (data) {
                if (data == 'save') {

                    var o = new ActionModels();

                    oCols.eq(0).text(o.actpersonid);
                    oCols.eq(1).text(o.actperson);
                    oCols.eq(2).html(o.actcontent);
                    oCols.eq(3).text(o.rptdte);

                }
                $('#div-dailog-edit').dialog('close');
            });
        });

        $('#open-search').click(function () {
            var title = '選擇負責人', url = '/account/search';
            var c = 'txtactperson';
            OpenSearchDailog('#div-dailog-search', title, url, function (ret) {
                if (ret == 'select') {
                    var rows = $('#dgSearch').datagrid('getSelections');
                    var id = [], name = [];
                    for (var i = 0; i < rows.length; i++) {
                        var row = rows[i];
                        id.push(row[PushFieldValue('account', 'id')]);
                        name.push(row[PushFieldValue('account', 'name')]);
                    }

                    $('#' + c).val(name.join(','));
                    $('#' + c + '_f').val(id.join(','));
                }

                CloseDialog('#div-dailog-search');

            });
        });

        $(document).delegate('.btn-save', 'click', function() {
            var listsysid = $(this).parents('#listdetail').data('listsysid');
            var meetsysid = $(this).parents('#listdetail').data('meetsysid');

            var alistdetails = new Array();
            var savemodel = {};

            savemodel.Meetsysid = meetsysid;
            savemodel.Listsysid = listsysid;

            $(this).parents('table').find('tbody tr').each(function() {
                var oCols = $(this).children('td');
                var listdetail = {};
                listdetail.Actpersonid = oCols.eq(0).text();
                listdetail.Actcontent = oCols.eq(2).text();
                listdetail.Rptdte = oCols.eq(3).text();
                alistdetails.push(listdetail);
            });
            savemodel.values = alistdetails;

            PostRequest('/meetfinish/saveactdetail', savemodel, function (ret) {
                if (ret.result) {
                    $.messager.alert('提示', '保存成功', 'info');
                } else {
                    $.messager.alert('提示', ret.errmsg, 'info');
                }
            });
        });

        function loadlist(data) {
            var ipos;
            var t = [], d5 = [];
            t = data.rows;

            var actdetail = [];

//            for (var i = 0; i < t.length; i++) {
//                var t2 = t[i];

            //d5 = t2.listitems; //事項列表
            d5 = data.rows;

            //事項列表
            for (ipos = 0; ipos < d5.length; ipos++) {
                var listdetail = d5[ipos];
                var acontent = listdetail.content.split('\n');

                var actcontent = '';
                var content = '<div style="padding:1px;overflow:auto;" id="listdetail" data-listsysid="' + listdetail.listsysid + '" data-meetsysid="' + listdetail.meetsysid + '">' + acontent.join('</br>');
                content += '<hr/>';
                content += '<table class="bordered" width=100%>';
                content += '<thead>';
                content += '<tr>';
                content += '<th style="display:none">actid</th>';
                content += '<th>負責人</th>';
                content += '<th width=50%>行動</th>';
                content += '<th>報告日期</th>';
                content += '<th>' + btnNew + ' ' + btnSave + '</th>'; // '<th><a href="javascript:void(0)" id="btn-new">操作</a></th>';
                content += '</tr>';
                content += '</thead>';
                content += '<tbody>';

                //行動事項
                actdetail = listdetail.ActDetails;
                for (var j = 0; j < actdetail.length; j++) {
                    var actdtl = actdetail[j];
                    if (listdetail.listsysid == actdtl.Listsysid) {

                        actcontent += '<tr><td style="display:none">' + actdtl.Actpersonid + '</td><td>' + actdtl.Actpersonname + '</td><td>' + actdtl.Actcontent + '</td><td>' + actdtl.Rptdte + '</td><td>' + btnEdit + '|' + btnDel + '</td></tr>';

                    }
                }
                content += actcontent;
                content += '</tbody>';
                content += '</table>';
                content += '</div>';

                $('#div-list-panels').accordion('add', {
                    title: listdetail.title,
                    content: content
                });

                //*******************
            }
//            }
        }
        function removeAllPanel() {
            //removeAllPanel('.div-list-panels');
            $('#div-list-panels .panel .panel-title').each(function () {
                $('#div-list-panels').accordion('remove', $(this).html());
            });
        }
        function ActionModels() {
            var self = this;

            self.actpersonid = $('#txtactperson_f').val();
            self.actperson = $('#txtactperson').val();
            self.actcontent = $('#txtactcontent').val().replace('/\n/g', '<br/>');
            self.rptdte = $('#txtrptdte').val();

            //alert(self.actcontent);
        }

        function ClearActionModels() {
            var self = this;

            self.actpersonid = '';
            self.actperson = '';
            self.actcontent = '';
            self.rptdte = '';

            $('#txtactperson_f').val('');
            $('#txtactperson').val('');
            $('#txtactcontent').val('');
            $('#txtrptdte').val('');
        }

        //從返回的表格行數中設置文本的值
        //rows:表格行數數組
        function SetDGSelections(rows, t) {
            var f1 = '', f2 = '';

            //                if (t == 'list') {
            //                    f1 = rows.ListName;
            //                    f2 = rows.ListSysId;
            //                }
            //                else if (t == 'account') {

            f1 = rows.FulName;
            f2 = rows.UserId;
            //                }

            $('#txtactperson').val(f1);
            $('#txtactperson' + '_f').val(f2);

            CloseDialog('#div-dailog-search');
        }

    </script>
</body>
</html>